core/urls.py
from django.contrib import admin
from django.urls import path, include
from core import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sms.urls', namespace='sms')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sms/urls.py
from django.urls import path
from sms.views.list_views import *

app_name = 'sms'

urlpatterns = [
    # views
    path('list/', \
        SmsListView.as_view(), \
        name='sms-list'),
]

core/models.py
from datetime import datetime
from django.db import models


class Template(models.Model):
    status = models.BooleanField(default=True) 
    create_dt = models.DateTimeField(default=datetime.now) 

    class Meta:
        abstract = True

sms/models.py
from random import choices
from django.db import models
from core.models import Template
from user.models import User


class SmsClass(models.Model):
    CLASS_CHOICES = {
        (1, 'Personal'),
        (2, 'Fraud'),
        (3, 'Advertisement'),
    }

    type = models.IntegerField(choices = CLASS_CHOICES) 

class Sms(Template, models.Model):
    sender = models.ForeignKey(User,
        on_delete=models.CASCADE,
        related_name='sender')
    recipient = models.ForeignKey(User,
        on_delete=models.CASCADE,
        related_name='recipient')
    message = models.TextField(null=True, blank=True)
    type = models.ForeignKey(SmsClass, on_delete=models.CASCADE)

user/models.py
from django.db import models
from core.models import Template

class User(Template, models.Model):
    phone_number = models.TextField(max_length=255)

sms/views/list_views.py
from django.shortcuts import render
from django.views.generic import View
from sms.apis.sms_apis import SmsApi

class SmsListView(View):
    @classmethod
    def get(cls, request):
        user_id = request.GET['user_id']
        target_id = request.GET.get('target_id')

        phone_number_list, sms_list, target_number = SmsApi.get_group_list(user_id, target_id)
        
        context = {
            'phone_number_list' : phone_number_list,
            'sms_list' : sms_list,
            'target_number' : target_number,
        }

        return render(request, 'sms/messages/list.html', context)
    
    @classmethod
    def post(cls, request):

        recipient_number = request.POST['recipient']
        sender_id = request.GET['user_id']
        message = request.POST['message']

        target_id = SmsApi.store_message(sender_id, recipient_number, message)
        
        user_id = request.GET['user_id']
        phone_number_list, sms_list, target_number = SmsApi.get_group_list(user_id, target_id)
        
        context = {
            'phone_number_list' : phone_number_list,
            'sms_list' : sms_list,
            'target_number' : target_number,
        }

        return render(request, 'sms/messages/list.html', context)

user/views.py
from django.shortcuts import render

# Create your views here.

sms/templates/sms/messages/list.html
{% load static %}

{% block link %}
<link rel="stylesheet" href="{% static 'sms/list/mlist.css' %}">
<style>
    ::placeholder { /* Chrome, Firefox, Opera, Safari 10.1+ */
        color: white;
        opacity: 1; /* Firefox */
      }
    ul {
        list-style-type: none;
    }
</style>
{% endblock %}

{% load sms_filter %}

{% block content %}
<div class="container clearfix">
    <div class="people-list" id="people-list">
        <div class="search">
        <input type="text" style="color:white" placeholder="search" />
        <i class="fa fa-search"></i>
    </div>

    <center>
        <a class="button" href="{% url 'sms:sms-list' %}?user_id={{request.GET.user_id}}"> New Message </a>
    </center>

    <ul class="list">
        {% for number in phone_number_list %}
        <li class="card clearfix">
            {% comment %} <div class="card"> {% endcomment %}
                {% if number.type == 1 %}
                <div class="alert-fraud">
                    Fraud
                </div>
                {% endif %}
                
                {% if number.type == 2 %}
                <div class="alert-ad">
                    Ad
                </div>
                {% endif %}
                
                <a href="{% url 'sms:sms-list' %}?user_id={{request.GET.user_id}}&target_id={{number.user_id}}" style="color:white">
                    <div class="about">
                        <div class="name">{{number.phone_number}}</div>
                        {{number.create_dt}}
                        <p>{{number.message|message_summary}}</p>
                    </div>
                </a>
            {% comment %} </div> {% endcomment %}
        </li>
        {% endfor %}
    </ul>
</div>

<div class="chat">
    <div class="chat-header clearfix">
        
        {% if target_number != '' %}
        <div class="chat-about">
            <div class="chat-with">{{target_number}}</div>
            <div class="chat-num-messages">already {{sms_list|length}} messages</div>
        </div>
        <i class="fa fa-star"></i>
    </div> <!-- end chat-header -->
    
    <div class="chat-history">
        <ul>
            {% for message in sms_list %}
                {% if message.sender == 0 %}
                <li class="clearfix">
                    <div class="message-data align-right">
                        <span class="message-data-time" >{{message.create_dt}}</span> &nbsp; &nbsp;
                        <span class="message-data-name" >me</span> <i class="fa fa-circle me"></i>
                    </div>
                    <div class="message other-message float-right">
                        {{message.message}}
                    </div>
                </li>
                {% else %}
                <li>
                    <div class="message-data">
                        <span class="message-data-name"><i class="fa fa-circle online"></i>Him/Her</span>
                        <span class="message-data-time">{{message.create_dt}}</span>
                    </div>
                    <div class="message my-message">
                        {{message.message}}
                    </div>
                </li>
                {% endif %}
                {% endfor %}
            </ul>
    </div> <!-- end chat-history -->
    {% endif %}
      
    <form method="POST">
        {% csrf_token %}
        <div class="chat-message clearfix">
            {% if target_number == '' %}
                Recipient : <input id="recipient" type="text" name="recipient" placeholder ="Type your message" rows="3"></input>
            {% else %}
                <input type="hidden" type="text" id="recipient" name="recipient" value="{{target_number}}" placeholder ="Type your message" rows="3"></input>
            {% endif %}
            <textarea name="message" id="message" placeholder ="Type your message" rows="3"></textarea>
            
            <input id="btn_submit" class="button-send" type="submit" value="kirim"></input>
        </div> <!-- end chat-message -->
    </form>
        
    
</div> <!-- end chat -->
    
</div> <!-- end container -->

{% endblock %}

{% block script %}
<script src="{% static 'sms/jquery/jquery.min.js' %}"></script>
<script src="{% static 'sms/listjs/list.min.js' %}"></script>
<script src="{% static 'sms/list/mlist.js' %}"></script>
<script src="{% static 'sms/list/messageform.js' %}"></script>
{% endblock %}